### PR TITLE
Escape '$' when launching Scalpel

### LINKED ISSUE #10: Escape special characters when starting Scalpel
Scalpel has "very magic" turned on by default. When editing PHP files (e.g. renaming variables). I find myself having to go back and escape the `$`. As ridiculous as it sounds, it's too much effort for me.

Would be good for Scalpel to automatically escape special characters on the search query.

### PR DESCRIPTION
**Pull request by kengkiat**
Fixes #10 

I've decided to only escape `$` as I can't think of any other special characters where this is useful. However, this can easily expanded to include other characters.

### CODE REVIEW

**Comment by wincent** [comment]
With something like this we have a few ways to do it:

- Change it straight up like you have here.
- Change it but make it optional (and if optional, decide whether to have the option off or on by default).
- Make it configurable (eg. let the user specify a list of characters to escape... `let g:ScalpelAutoEscape='$'`).
- Make it "smart" so that no configuration is necessary (eg. look for characters in the current filetype's `'iskeyword'` and see if any of them should be escaped).

I almost never want to do the first option, in case there's some use case I haven't thought about; I don't want to risk breaking somebody's usage scenario.

I think my preference here is basically in the order of the list above (from least to most preferred):

1. Change it for everybody.
2. Make it optional (off by default).
3. Make it optional (on by default).
4. Make it configurable.
5. Make it "smart".

The only risk is that sometimes "smart" things end up being dumb. 😂 Any thoughts on this?

**Comment by wincent** [comment]
Ok, thinking about it, it seems that we can just blanket-escape anything that might have special meaning for `/\v`. I don't think there is risk of this breaking anybody's workflow, and I don't think we need to try and be "smart" and vary the behavior based on what's in `'iskeyword'`.

Thanks for the PR!

**Comment by kengkiat** [comment]
Sorry for the late response. I think it make sense to make it configurable (but with sensible defaults). Will probably submit another PR when I have the time.

**Comment by kengkiat** [comment]
Nvm... I see that it's done :)

**Pull request merged**
